steps:
  # Use Node.js 18 to build the Gatsby site
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    # Install dependencies

  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    # Build the Gatsby site

  # Use Docker to create a container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/new-website', '.']
    # Build a Docker image.
    #  - Replace 'new-website' with your desired image name.
    #  -  The '.' specifies the current directory (where the Dockerfile is located).
    #    You'll need a Dockerfile in your project root.

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/new-website']
    # Push the built image to Google Artifact Registry.

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'my-gatsby-service', # Replace with your desired service name
        '--image',
        'gcr.io/${PROJECT_ID}/new-website',
        '--region',
        'us-central1', # Or your desired region
        '--platform',
        'managed',
        '--allow-unauthenticated', # Adjust security as needed
      ]
    # Deploy the image to Cloud Run.
    #  - Replace 'my-gatsby-service' with your Cloud Run service name.
    #  -  Replace 'us-central1' with your desired deployment region.
    #  -  Consider security implications of `--allow-unauthenticated`.

options:
  logging: CLOUD_LOGGING_ONLY
