service: webiny-website-services

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
      Resource:
        - 'arn:aws:ses:us-east-1:*'

functions:
  subscribe:
    handler: subscribe.handler
    events:
      - http:
          path: subscribe
          method: post
  contact-us:
    handler: contact-us.handler
    events:
      - http:
          path: contact-us
          method: post
plugins:
  - serverless-offline
custom:
  serverless-offline:
    port: 4000